version: '3.7'
services:
  sql-server:
    container_name: sql-server
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: example_123
      attach_dbs: "[{'dbName':'TechChallenge','dbFiles':['/var/opt/mssql/data/HealthMedAgendamento.mdf' , '/var/opt/mssql/data/HealthMedAgendamento.ldf']}]"
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P example_123 -Q 'SELECT 1' || exit 1"]
        interval: 10s
        retries: 10
        start_period: 10s
        timeout: 3s
    ports:
      - "1433:1433"
    volumes:
      - C:\Data/SQLServerData:/var/opt/mssql/data
    
  api:
    container_name: fiap-healthmed_agendamento
    image: eltonmattos/healthmed_agendamento:latest
    ports:
      - "8080:8080"
      
networks:
  localprom:
    driver: bridge