# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - healthmedagendamento

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_b75208283f49468ca7611856258a7f86 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c9cc4c5902f74feab92a7b2fafff35f1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b75208283f49468ca7611856258a7f86 }}/healthmed_agendamento:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    
    steps:
    #- name: Deploy to Azure Web App
    #  id: deploy-to-webapp
    #  uses: azure/webapps-deploy@v2
    #  with:
    #    app-name: 'healthmedagendamento'
    #    slot-name: 'production'
    #    publish-profile: ${{ secrets.AzureAppService_PublishProfile_4abc10d81ec6464bbec0c9e9a2ee5ffe }}
    #    images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b75208283f49468ca7611856258a7f86 }}/healthmed_agendamento:${{ github.sha }}'

      - uses: actions/checkout@v2
      
      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.KUBECONFIG}}
          version: 1.21.0
          
      - name: Deploy to AKS
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          
      - name: Wait for AKS Deploy
        run: kubectl wait --for-condition=available
    
