# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - healthmedagendamento

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_92c8bd7a071346f592795e1adc7c6c7f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9ea71fd9d6824fa580af79982ee5edde }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_92c8bd7a071346f592795e1adc7c6c7f }}/eltonmattos/healthmed_agendamento:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'healthmedagendamento'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c45c357642564d74b24a952e733b35d9 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_92c8bd7a071346f592795e1adc7c6c7f }}/eltonmattos/healthmed_agendamento:${{ github.sha }}'