# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - healthmedagendamento

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: healthmedagendamento 
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0.x' 

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@main
  
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }} 
    
    - name: dotnet build and publish
      run: |
        dotnet restore
        dotnet build --configuration Release
    
    - name: Run tests
      run: dotnet test --no-build --configuration Release --verbosity normal
        
    - name: dotnet build and publish
      run: dotnet publish -c Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }/myapp}' 

    - name: Azure WebApp
      uses: Azure/webapps-deploy@v3.0.1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
        images: eltonmattos/healthmed_agendamento:latest
        # Applies to Web App Containers only: Path of the Docker-Compose file. Should be a fully qualified path or relative to the default working directory. Required for multi-container scenario
        # configuration-file: # optional

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PWD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/eltonmattos/healthmed_agendamento:latest
        file: ./Dockerfile
        
